name: Actions Worklfow

on: 
  #1 push:
  #2 pull_request:
  #2  types: [closed, assigned, opened, reopened]
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
    - name: Simple JS Action
      id: greet
      uses: /actions/hello-world-javascript-action@v1
      with:
        who-to-greet: Octo
    - name: log greeting time
      run: echo "${{ steps.greet.outputs.time }}"