name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: alialaa17/node-api
        ports:
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - "27017:27017"
    steps:
    - name: Post a user test
      run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json''' -d ''{"username": "hello", "address": "900 Startup Way"}'''
    - name: Get users
      run: curl http://localhost:3001/api/users