name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [6, 8, 10]
        exclude:
        - os: windows-latest
          node_version: 6
        - os: macos-latest
          node_version: 10
        include:
        - os: ubuntu-latest
          node_version: 8
          is_ubuntu_node_v8: "true"
      max-parallel: 3
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_NODEV8: ${{ matrix.is_ubuntu_node_v8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_NODEV8